version: 0.2
phases:
  install:
    commands:
      - echo Installing dependencies...
      - pip install -r frontend/requirements.txt || true
  build:
    commands:
      - echo Packaging application correctly...
      - cd frontend
      - zip -r ../app.zip *
artifacts:
  files:
    - app.zip
