version: 0.2
phases:
  install:
    commands:
      - echo Installing dependencies...
      - pip install -r frontend/requirements.txt || true
  build:
    commands:
      - echo Zipping application files...
      - cd frontend
      - zip -r ../app.zip app.py appspec.yaml scripts/ requirements.txt
artifacts:
  files:
    - frontend/app.zip
